dataset:
  name: nuScenes
  path: data/nuscenes/v1.0-mini
  # name: KITTI
  # path: data/kitti/training

filters:
  - name: range_filter
    range:
  - name: threshold_filter
    threshold:
  - name: type_filter
    black_type:
    white_type:
