inputs:
  - name: pointcloud
    type: bin
    path: data/custom/velodyne/000005.bin
  - name: oriented_bounding_box
    path: data/custom/label/000005.txt
    color: red

filters:
  - name: range_filter
    range: 
  - name: threshold_filter
    threshold:
  - name: type_filter
    black_type:
    white_type:
