inputs:
  - name: pointcloud
    type: bin
    path: data/kitti/training/velodyne/000003.bin
    transform: []
    color: red
  - name: pointcloud
    type: bin
    path: data/kitti/training/velodyne/000005.bin
    color: blue
